# Generated by Django 5.2.3 on 2025-06-29 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_типы_курсов_название'),
    ]

    operations = [
        migrations.RenameField(
            model_name='организации',
            old_name='Полное_название',
            new_name='Название',
        ),
        migrations.RemoveField(
            model_name='организации',
            name='Сокращенное_название',
        ),
    ]
