# Generated by Django 5.2.3 on 2025-06-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_полное_название_организации_название_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='материалы_курсов',
            name='Файл_материала',
        ),
        migrations.AddField(
            model_name='материалы_курсов',
            name='Название',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='материалы_курсов',
            name='Ссылка_на_файл',
            field=models.CharField(default='about:blank', max_length=255),
        ),
        migrations.AlterField(
            model_name='группы',
            name='Название',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='организации',
            name='ИНН',
            field=models.CharField(blank=True, default='1234567890', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='организации',
            name='Название',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='организации',
            name='ОГРН',
            field=models.CharField(blank=True, default='1234567890123', max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='слушатели',
            name='ИНН',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='страны',
            name='Краткое_название',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='страны',
            name='Название',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
