# Generated by Django 5.2.3 on 2025-06-29 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_материалы_курсов_файл_материала_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='материалы_курсов',
            old_name='Ссылка_на_файл',
            new_name='Ссылка_на_материал',
        ),
    ]
