# Generated by Django 5.2.3 on 2025-06-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_ссылка_на_файл_материалы_курсов_ссылка_на_материал'),
    ]

    operations = [
        migrations.AddField(
            model_name='человек_организация',
            name='Должность',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='слушатели',
            name='Телефон',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
