# Generated by Django 5.2.3 on 2025-06-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_человек_организация_должность_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='человек_организация',
            name='Должность',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
