# Generated by Django 5.2.3 on 2025-06-30 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_человек_организация_должность'),
    ]

    operations = [
        migrations.CreateModel(
            name='Протоколы',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Дата_создания', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Результат_проверки',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Статусы',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='группы',
            name='Объём_часов',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='человек_группа',
            name='Результат',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='человек_группа',
            name='Протокол',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.протоколы'),
        ),
        migrations.AddField(
            model_name='человек_группа',
            name='Статус',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.статусы'),
        ),
    ]
