# Generated by Django 5.2.3 on 2025-06-30 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_протоколы_результат_проверки_статусы_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='группы',
            name='Название',
        ),
        migrations.RemoveField(
            model_name='группы',
            name='Объём_часов',
        ),
        migrations.AddField(
            model_name='курсы',
            name='Объём_часов',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
