# Generated by Django 5.2.3 on 2025-06-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_группы_название_remove_группы_объём_часов_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='организации',
            name='Телефон',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='организации',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='организации',
            name='ИНН',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='организации',
            name='ОГРН',
            field=models.CharField(blank=True, max_length=13, unique=True),
        ),
    ]
