# Generated by Django 5.2.3 on 2025-07-01 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_организации_телефон_alter_организации_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='человек_группа',
            name='Протокол',
        ),
        migrations.DeleteModel(
            name='Результат_проверки',
        ),
        migrations.DeleteModel(
            name='Протоколы',
        ),
    ]
