# Generated by Django 5.2.3 on 2025-07-01 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_человек_группа_протокол_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='человек_группа',
            name='Результат',
        ),
    ]
