# Generated by Django 5.2.3 on 2025-07-01 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_человек_группа_результат'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='дома',
            name='id_улицы',
        ),
        migrations.RemoveField(
            model_name='населенные_пункты',
            name='тип',
        ),
        migrations.RemoveField(
            model_name='улицы',
            name='Почтовый_индекс',
        ),
        migrations.RemoveField(
            model_name='районы',
            name='Регион',
        ),
        migrations.RemoveField(
            model_name='регионы',
            name='Страна',
        ),
        migrations.RemoveField(
            model_name='улицы',
            name='тип',
        ),
        migrations.DeleteModel(
            name='Адреса',
        ),
        migrations.DeleteModel(
            name='Дома',
        ),
        migrations.DeleteModel(
            name='Населенные_пункты',
        ),
        migrations.DeleteModel(
            name='Типы_населенных_пунктов',
        ),
        migrations.DeleteModel(
            name='Почтовые_индексы',
        ),
        migrations.DeleteModel(
            name='Районы',
        ),
        migrations.DeleteModel(
            name='Регионы',
        ),
        migrations.DeleteModel(
            name='Типы_улиц',
        ),
        migrations.DeleteModel(
            name='Улицы',
        ),
    ]
