# Generated by Django 5.2.3 on 2025-07-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_дома_id_улицы_remove_населенные_пункты_тип_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Месяцы',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название', models.CharField(max_length=8)),
            ],
        ),
    ]
