# Generated by Django 5.2.3 on 2025-07-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_пол_название'),
    ]

    operations = [
        migrations.AlterField(
            model_name='пол',
            name='Название',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
