# Generated by Django 5.2.3 on 2025-07-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_пол_название'),
    ]

    operations = [
        migrations.AlterField(
            model_name='организации',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='организации',
            name='Телефон',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
