# Generated by Django 5.2.3 on 2025-07-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_организации_email_alter_организации_телефон'),
    ]

    operations = [
        migrations.AlterField(
            model_name='слушатели',
            name='ИНН',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
