# Generated by Django 5.2.3 on 2025-07-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_слушатели_инн'),
    ]

    operations = [
        migrations.CreateModel(
            name='Протоколы',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Дата_составления', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='человек_группа',
            name='Результат',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='слушатели',
            name='Дата_рождения',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='слушатели',
            name='Номер_паспорта',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
