# Generated by Django 5.2.3 on 2025-07-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_протоколы_человек_группа_результат_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Результат',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
