# Generated by Django 5.2.3 on 2025-07-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_человек_группа_результат'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='человек_группа',
            name='Результат',
        ),
        migrations.AlterField(
            model_name='статусы',
            name='Название',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Результат',
        ),
    ]
