# Generated by Django 5.2.3 on 2025-07-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_человек_группа_результат_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Приказы',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('тип', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='группы',
            name='Дата_начала_курса',
        ),
        migrations.RemoveField(
            model_name='группы',
            name='Дата_окончания_курса',
        ),
    ]
