# Generated by Django 5.2.3 on 2025-07-04 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_приказы_remove_группы_дата_начала_курса_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='приказы',
            old_name='тип',
            new_name='Тип',
        ),
    ]
