# Generated by Django 5.2.3 on 2025-07-04 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_rename_тип_приказы_тип'),
    ]

    operations = [
        migrations.RenameField(
            model_name='приказы',
            old_name='Тип',
            new_name='Hash',
        ),
    ]
