# Generated by Django 5.2.3 on 2025-07-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_rename_тип_приказы_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='приказы',
            name='Hash',
            field=models.BigIntegerField(),
        ),
    ]
