# Generated by Django 5.2.3 on 2025-07-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_приказы_hash_alter_протоколы_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Удостоверения',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hash', models.IntegerField(null=True)),
            ],
        ),
    ]
