# Generated by Django 5.2.3 on 2025-07-05 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_удостоверения'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Удостоверения',
        ),
    ]
