# Generated by Django 5.2.3 on 2025-07-05 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_delete_удостоверения'),
    ]

    operations = [
        migrations.CreateModel(
            name='Адреса',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Номер_дома', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Почтовые_индексы',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Индекс', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Типы_населенных_пунктов',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Типы_улиц',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='организации',
            name='Адрес',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.адреса'),
        ),
        migrations.AddField(
            model_name='слушатели',
            name='Адрес',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.адреса'),
        ),
        migrations.CreateModel(
            name='Регионы',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Код', models.CharField(max_length=10)),
                ('Название', models.CharField(max_length=100)),
                ('Страна', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.страны')),
            ],
        ),
        migrations.CreateModel(
            name='Районы',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название', models.CharField(max_length=100)),
                ('Регион', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.регионы')),
            ],
        ),
        migrations.CreateModel(
            name='Населенные_пункты',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название', models.CharField(max_length=100)),
                ('Район', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.районы')),
                ('тип', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.типы_населенных_пунктов')),
            ],
        ),
        migrations.CreateModel(
            name='Названия_улиц',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название', models.CharField(max_length=100)),
                ('Тип_улицы', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.типы_улиц')),
            ],
        ),
        migrations.CreateModel(
            name='Улицы',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.названия_улиц')),
                ('Населенный_пункт', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.населенные_пункты')),
                ('Почтовый_индекс', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.почтовые_индексы')),
            ],
        ),
        migrations.AddField(
            model_name='адреса',
            name='улица',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.улицы'),
        ),
    ]
