# Generated by Django 5.2.3 on 2025-07-06 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_адреса_почтовые_индексы_типы_населенных_пунктов_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='улицы',
            name='Населенный_пункт',
        ),
        migrations.AddField(
            model_name='почтовые_индексы',
            name='Населенный_пункт',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.населенные_пункты'),
        ),
    ]
