# Generated by Django 5.2.3 on 2025-07-06 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_remove_улицы_населенный_пункт_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='названия_улиц',
            name='Тип_улицы',
        ),
        migrations.DeleteModel(
            name='Типы_улиц',
        ),
    ]
