# Generated by Django 5.2.3 on 2025-07-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_названия_улиц_тип_улицы_delete_типы_улиц'),
    ]

    operations = [
        migrations.AlterField(
            model_name='месяцы',
            name='Название',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
