# Generated by Django 5.2.3 on 2025-07-06 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_типы_населенных_пунктов_название'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='регионы',
            name='Код',
        ),
    ]
