# Generated by Django 5.2.3 on 2025-07-06 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_remove_регионы_код'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='организации',
            name='Адрес',
        ),
        migrations.RemoveField(
            model_name='слушатели',
            name='Адрес',
        ),
        migrations.CreateModel(
            name='Адреса_организаций',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Адрес', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.адреса')),
                ('Организация', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.организации')),
            ],
        ),
        migrations.CreateModel(
            name='Адреса_слушателей',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Адрес', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.адреса')),
                ('Слушатель', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.слушатели')),
            ],
        ),
    ]
