# Generated by Django 5.2.3 on 2025-07-06 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_почтовые_индексы_населенный_пункт_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='адреса_организаций',
            name='Адрес',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.адреса', unique=True),
        ),
        migrations.AlterField(
            model_name='адреса_организаций',
            name='Организация',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.организации', unique=True),
        ),
        migrations.AlterField(
            model_name='адреса_слушателей',
            name='Адрес',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.адреса', unique=True),
        ),
        migrations.AlterField(
            model_name='адреса_слушателей',
            name='Слушатель',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.слушатели', unique=True),
        ),
        migrations.AlterField(
            model_name='названия_улиц',
            name='Название',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='почтовые_индексы',
            name='Индекс',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='регионы',
            name='Страна',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.страны', unique=True),
        ),
    ]
