# Generated by Django 5.2.3 on 2025-07-06 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_адреса_организаций_адрес_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='регионы',
            name='Страна',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.страны'),
        ),
    ]
