# Generated by Django 5.2.3 on 2025-07-06 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_регионы_страна'),
    ]

    operations = [
        migrations.AlterField(
            model_name='адреса_организаций',
            name='Адрес',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.адреса'),
        ),
        migrations.AlterField(
            model_name='адреса_организаций',
            name='Организация',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.организации'),
        ),
        migrations.AlterField(
            model_name='адреса_слушателей',
            name='Адрес',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.адреса'),
        ),
        migrations.AlterField(
            model_name='адреса_слушателей',
            name='Слушатель',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.слушатели'),
        ),
        migrations.AlterField(
            model_name='почтовые_индексы',
            name='Индекс',
            field=models.CharField(max_length=10),
        ),
    ]
