# Generated by Django 5.2.3 on 2025-07-07 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_alter_адреса_организаций_адрес_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='населенные_пункты',
            name='Регион',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.регионы'),
        ),
        migrations.AlterField(
            model_name='населенные_пункты',
            name='Район',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.районы'),
        ),
    ]
