# Generated by Django 5.2.3 on 2025-07-07 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_населенные_пункты_регион_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='населенные_пункты',
            name='тип',
        ),
        migrations.DeleteModel(
            name='Типы_населенных_пунктов',
        ),
    ]
